name: Publish release to PyPI

on:
  push:
    branches:
    - main

jobs:
  publish_pypi_release:
    runs-on: ubuntu-latest
    environment: pypi
    continue-on-error: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Bump package version
      run: |
        python .github/bump_version.py

    - name: Build package
      run: poetry build

    - name: Publish to TestPyPI
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry publish -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_API_KEY }}

    - name: Publish to PyPI
      run: |
        poetry publish -u __token__ -p ${{ secrets.PYPI_API_KEY }}
