name: Test demos
on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  test-demos:
    name: Test demos
    uses: unifyai/console/.github/workflows/test-demos.yml@main
