name: Test demos
on:
  workflow_dispatch:
#   push:
#     branches:
#     - main
# permissions:
#   contents: write
#   actions: read
#   id-token: write

jobs:
  test-demos:
    name: Test demos
    uses: unifyai/workflows/.github/workflows/test-demos.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.CONSOLE_TOKEN }}
